### ISSUE TITLE
segfault in openssl_probe call from native-tls on recent alpine

### ISSUE THREAD

**Issue by erikh** [alexcrichton/openssl-probe#19]
I'm seeing this debugging an issue with a DNS server I'm working on. The issue is here: https://github.com/zerotier/zeronsd/issues/106

I'm throwing it over the fence for educated eyeballs, but will debug and report back when I know more about what's causing it. I'm fairly certain something messy in the environment is causing the issue.

Hope this is useful, if you don't know what's going on or don't want to investigate, I will report back in a day or two.

**Comment by alexcrichton** [comment]
Sorry I don't know much about how this crate could cause a segfault myself :(

**Comment by erikh** [comment]
yeah, kind of jumped the gun here. sorry.
