### ISSUE TITLE
Add function to check for success at runtime

### ISSUE THREAD

**Issue by timvisee** [alexcrichton/openssl-probe#7]
At this time I don't believe it is possible to check whether `openssl-probe` or `openssl` itself found the CA certificates it needs at runtime.

I would like to be able to check this, to inform end users that certificates couldn't be found and that they must be installed.

Would it be an idea to let us check whether certificates are found after probing at runtime, possibly by returning a `Result` by the probe function? Or is this already possible using the `openssl` crate itself and am I missing something?

I'm happy to open a PR once I know such functionality is desired, and know how to approach such thing.

**Comment by alexcrichton** [comment]
Sounds plausible to me!
